pipelines:
  pull-requests:
    '**':
      - step:
          name: "Unit test"
          image: yanisipedis/php7.4-amqp:0.2
          script:
            - composer install
            - bin/test.sh
          caches:
            - composer
